version: '2'

services:

  templates:
    restart: always
    image: portainer/templates
    container_name: "portainer-templates"
    networks:
      - local

  portainer:
    restart: always
    image: portainer/portainer
    container_name: "portainer-app"
    command: --templates http://templates/templates.json
    networks:
      - local
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data

  watchtower:
    restart: always
    image: centurylink/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  local:
    driver: bridge